# fly.toml file generated for svelte-catchup on 2023-04-01T01:16:56+02:00

app = "svelte-catchup"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []
primary_region = "cdg"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  script_checks = []

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
